name: CI - Lint & Build (Bun)

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXT_AUTH_APP_URL }}
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Lint with ESLint & Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '.'
          fail_on_error: true

      - name: ✅ Check Environment Variables
        run: |
          echo "Checking required environment variables..."
          test -n "$API_URL" && echo "✅ API_URL is set" || (echo "❌ API_URL is missing" && exit 1)
          test -n "$NEXTAUTH_SECRET" && echo "✅ NEXTAUTH_SECRET is set" || (echo "❌ NEXTAUTH_SECRET is missing" && exit 1)
          test -n "$NEXTAUTH_URL" && echo "✅ NEXTAUTH_URL is set" || (echo "❌ NEXTAUTH_URL is missing" && exit 1)
          test -n "$NEXT_PUBLIC_APP_URL" && echo "✅ NEXT_PUBLIC_APP_URL is set" || (echo "❌ NEXT_PUBLIC_APP_URL is missing" && exit 1)

      - name: Build Project
        run: bun run build

      - name: Notify failure
        if: failure()
        run: echo "❌ Lint or Build failed. Check PR comments or logs."
