name: CI - Lint & Build (Bun)

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXT_AUTH_APP_URL }}
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      # 1. Lint and generate JSON report
      - name: Run ESLint Check (Soft Fail)
        id: lintcheck
        run: |
          bunx eslint . --output-file eslint-report.json --format json || true

      # 2. Reviewdog to comment on PR
      - name: Reviewdog - Report ESLint Issues
        if: always()
        uses: reviewdog/action-reviewdog@v1
        with:
          name: eslint
          reporter: github-pr-review
          level: warning
          fail_on_error: false
          filter_mode: added
          tool_name: eslint
          input: eslint-report.json
          format: eslint

      # 3. Env check
      - name: Check Required Environment Variables
        id: envcheck
        run: |
          echo "Checking required environment variables..."
          failed=0
          for var in API_URL NEXTAUTH_SECRET NEXTAUTH_URL NEXT_PUBLIC_APP_URL; do
            if [ -z "${!var}" ]; then
              echo "❌ Missing $var"
              failed=1
            else
              echo "✅ $var is set"
            fi
          done
          echo "env_status=$failed" >> $GITHUB_OUTPUT

      # 4. Try building and save logs
      - name: Build Project
        id: build
        run: |
          bun run build 2>&1 | tee build.log
        continue-on-error: true

      # 5. Summarize build log if it failed
      - name: Upload Build Log to PR Summary (if failed)
        if: failure()
        run: |
          echo "### ❌ Build Failed" >> $GITHUB_STEP_SUMMARY
          echo '```log' >> $GITHUB_STEP_SUMMARY
          tail -n 50 build.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      # 6. Final status: fail if envs or build failed
      - name: Final Status Check
        if: always()
        run: |
          if [[ "${{ steps.envcheck.outputs.env_status }}" == "1" ]]; then
            echo "❌ Missing one or more required environment variables"
            exit 1
          fi

          if [[ "${{ steps.build.outcome }}" == "failure" ]]; then
            echo "❌ Build failed"
            exit 1
          fi

          echo "✅ All checks passed"
          
