name: CI - Lint, Build, and Env Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint-build-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      API_URL: ${{ secrets.API_URL }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXT_AUTH_APP_URL }}
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Install ESLint and Reviewdog (dev deps)
        run: |
          bun add -d eslint
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b . latest

      - name: Run ESLint via Reviewdog
        continue-on-error: true
        run: |
          bunx eslint . -f json | tee eslint_output.json | ./reviewdog -f=eslint -name="eslint" -reporter=github-pr-review

      - name: Check Environment Variables
        run: |
          echo "Checking required ENV variables..."
          test -n "$API_URL" && echo "API_URL loaded"
          test -n "$NEXT_PUBLIC_APP_URL" && echo "NEXT_PUBLIC_APP_URL loaded"
          test -n "$NEXTAUTH_SECRET" && echo "NEXTAUTH_SECRET loaded"
          test -n "$NEXTAUTH_URL" && echo "NEXTAUTH_URL loaded"

      - name: Build Project
        id: build
        continue-on-error: true
        run: |
          bun run build 2>&1 | tee build.log || echo "::set-output name=failure::true"

      - name: Report Build Failure in Summary (if any)
        if: steps.build.outcome == 'failure'
        run: |
          echo "### ❌ Build Failed" >> $GITHUB_STEP_SUMMARY
          echo '```log' >> $GITHUB_STEP_SUMMARY
          tail -n 50 build.log >> $GITHUB_STEP_SUMMARY || echo "No build log found."
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Comment Build Failure on PR (with log tail)
        if: steps.build.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const logs = fs.readFileSync('build.log', 'utf-8').split('\n').slice(-50).join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Build failed.**\n\n\`\`\`log\n${logs}\n\`\`\``
            });

      - name: Comment Setup Success on PR
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ All setup completed. Ready to deploy on server."
            })
